version: "3.9"

services:

  web-based-terminal:
    container_name: web-based-terminal
    image: ghcr.io/billchurch/webssh2:latest
    ports:
      - "2222:2222"
    networks:
      - ans-labs-net

  # backend
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - ans-labs-net
  
  # frontend
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ans-labs-net
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

# networks
networks:
  ans-labs-net:
    name: ans-labs-net
    driver: bridge